settings:
  docker:
    parent_image: 122610508479.dkr.ecr.us-east-1.amazonaws.com/zenml-lbynmz
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false
    
parameters:
  author_full_names:
    - Maxime Labonne
    - Paul Iusztin
