settings:
  docker:
    parent_image: 122610508479.dkr.ecr.us-east-1.amazonaws.com/zenml-lbynmz
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  test_split_size: 0.05
  dataset_type: "preference"
  push_to_huggingface: true
  dataset_id: Oysiyl/llmtwin-dpo
  mock: true
